#pragma once
#include "bindings.h"
struct daTag_Hint_c : fopAc_ac_c {
  be<u32> m290;
  be<s8> m294;
  u8 pad[3];
  be<u32> mMsgNo;
  be<s32> m29C;
  be<s16> m2A0;
  be<u8> mCurProc;
  be<u8> m2A3;
  be<s16> m2A4;
  be<u16> m2A6;
  be<f32> m2A8;
  be<f32> m2AC;
  be<f32> m2B0;
  u8 getEventNo();
  u8 getSwbit();
  u8 getSwbit2();
  u8 getType();
  u8 getType2();
  u16 getEventFlag();
  s32 rangeCheck_local(cXyz *);
  s32 rangeCheck();
  s32 moveBoxCheck();
  s32 waitTerms();
  s32 arrivalTerms();
  void darkProc();
  s32 actionLight();
  u16 getMessage();
  u32 getMsg();
  void talkInit();
  s32 getPriority();
  s32 otherCheck();
  void makeEventId();
  void startProc();
  void setPlayerAngle();
  s32 actionHunt();
  s32 actionArrival();
  void initLight();
  void setLightPos();
  void makeLight();
  void deleteLight();
  u16 next_msgStatus(u32 *);
  u16 talk();
  s32 actionEvent();
};
WWHD_OFFSET(daTag_Hint_c, m2A0, 0x3BC);
WWHD_OFFSET(daTag_Hint_c, m2B0, 0x3CC);
WWHD_SIZE(daTag_Hint_c, 0x3D0);
