/* WWHD bomb flower layouts, checked against the original actor code. */
#pragma once
#include "bindings.h"
namespace daBomb2 {
struct Brk_l : mDoExt_baseAnm {
  u8 bytes[0x68];
  void entry(J3DModelData *p, f32 f) { gabi::call(0x025E83FC, this, p, f); }
};
struct Env_c {
  LIGHT_INFLUENCE mPntLight;
  u8 wind[0x2C];
  be<u8> field_0x4C;
  u8 pad[3];
  be<f32> field_0x50;
  void set(const cXyz *);
  void clean();
  bool is_end();
  void proc(const cXyz *);
};
struct FuseSmokeCB_c {
  be<u32> vt;
  be<s16> field_0x04;
  u8 pad[2];
  gptr<const cXyz> mpPos, field_0x0C, field_0x10;
  gptr<void> mpEmitter;
  void setOldPosP(const cXyz *, const cXyz *);
  void deleteCallBack();
  void executeAfter(void *);
};
struct FuseSparksCB_c {
  be<u32> vt;
  gptr<const cXyz> mpPos;
  gptr<void> mpEmitter;
  void deleteCallBack();
  void execute(void *);
};
struct Act_c : fopAc_ac_c {
  request_of_phase_process_class mPhase;
  gptr<J3DModel> mpModel;
  mDoExt_bckAnm mBck0;
  Brk_l mBrk0;
  dBgS_Acch mAcch;
  dBgS_AcchCir mCir;
  u8 ground[0x54];
  be<f32> field_0x51C, field_0x520;
  be<u8> field_0x524, mbWaterIn, field_0x526;
  u8 pad71F;
  be<f32> field_0x528;
  dCcD_Stts mStts;
  dCcD_Sph mSph;
  be<s32> mState, field_0x698;
  FuseSmokeCB_c mSmoke;
  FuseSparksCB_c mSparks;
  cXyz field_0x6C0, field_0x6CC, field_0x6D8;
  Env_c mEnv;
  be<s32> mBombTimer, field_0x73C;
  be<u8> field_0x740, field_0x741, field_0x742, field_0x743, field_0x744,
      field_0x745;
  u8 pad942[2];
  cXyz mWindVec;
  be<f32> field_0x754[12];
  be<f32> field_0x784, field_0x788, field_0x78C, field_0x790, field_0x794,
      field_0x798, field_0x79C, field_0x7A0, field_0x7A4;
  be<s32> field_0x7A8;
  bool create_heap_nut();
  u32 create_heap();
  void crr_init();
  void cc_init();
  void start_explode_instant();
  void start_explode_interval();
  void start_carry();
  void start_proc_call();
  void create_init();
  cPhs_State _create();
  bool _delete();
  void set_mtx();
  void init_mtx();
  void cc_set();
  void camera_lockoff();
  void posMoveF();
  void bgCrrPos();
  void bgCrrPos_lava();
  void bgCrrPos_water();
  u8 chk_water_in();
  bool chk_lava_in();
  void setRoomInfo();
  void bound(f32 value);
  void set_nut_exp_interval();
  void anm_play();
  void set_wind_vec();
  void eff_explode();
  void eff_explode_normal(const csXyz *angle);
  void eff_explode_water();
  void eff_fuse_init();
  void eff_fuse_start();
  void eff_fuse_move();
  void eff_fuse_end();
  void eff_water_splash();
  void se_fall_water();
  void se_explode();
  void se_explode_water();
  void se_ignition();
  void set_sound_env(s32 a, s32 b);
  bool chk_exp_cc_nut();
  u32 chk_exp_cc();
  bool chk_exp_bg_nut();
  bool chk_exp_bg();
  bool chk_exp_timer();
  bool chk_sink_bg_nut();
  bool chk_sink_bg();
  u8 chk_exp_pre();
  u8 chk_exp_post();
  u8 chk_sink_post();
  void set_real_shadow_flag();
  void carry_fuse_start();
  void on_carry();
  void off_carry();
  void mode_wait_init();
  void mode_wait();
  void mode_carry_init();
  void mode_carry();
  void mode_explode_init();
  void mode_explode();
  void mode_sink_init();
  void mode_sink();
  void mode_proc_call();
  void tensor_init();
  void vib_init();
  void vib_proc();
  void set_vib_tensor();
  void tensor_wait();
  void tensor_wait_drop();
  void tensor_wait_ground();
  void tensor_carry();
  void tensor_explode();
  void tensor_sink();
  void tensor_proc_call();
  bool _execute();
  bool is_draw();
  void draw_nut();
  bool _draw();
};
WWHD_SIZE(Env_c, 0x58);
WWHD_OFFSET(Act_c, mAcch, 0x4BC);
WWHD_OFFSET(Act_c, mSph, 0x760);
WWHD_OFFSET(Act_c, mEnv, 0x8DC);
WWHD_OFFSET(Act_c, mBombTimer, 0x934);
WWHD_SIZE(Act_c, 0x9A8);
} // namespace daBomb2
