/* WWHD sea rafts and ships. */
#pragma once
#include "bindings.h"
namespace ikada {
struct WaveCallback_l {
    u8 _00[8];
    be<f32> mSpeed;
    u8 _0C[4];
    be<f32> mMaxDisSpeed, mPitch, mMaxSpeed;
    cXyz mAnchor0, mAnchor1;
    u8 _34[0x2C];
    be<u32> mpEmitter;
};
struct SplashCallback_l {
    u8 _00[8];
    be<f32> mSpeed, mMaxSpeed;
    u8 _10[8];
    be<u32> mpEmitter;
};
struct TrackCallback_l {
    u8 _00[4];
    be<u16> mStop;
    u8 _06[2];
    be<f32> mWaterY, mWaterFlatY;
    u8 _10[0x2C];
    be<f32> mIndTransY, mIndScaleY, mSpeed, mLimitSpeed;
    be<u32> mpEmitter;
};
struct FollowCallback_l {
    u8 _00[4];
    be<u32> mpEmitter;
    u8 _08[12];
};
struct RippleCallback_l {
    u8 _00[4];
    be<u32> mpEmitter;
    u8 _08[8];
    be<f32> mRate;
};
struct Wave_l {
    be<f32> mPhase;
    be<s16> mAnimX, mAnimZ, mRotX, mRotZ;
};
struct Actor : fopAc_ac_c {
    be<s32> mType;
    be<u32> m0294, m0298, m029C, m02A0;
    be<u8> mPathId;
    u8 _3C1[3];
    cXyz mCurPathP0;
    be<s8> mCurPathPoint;
    u8 _3D1[3];
    be<u32> mpPath;
    u8 _3D8[4];
    cXyz mCurPathP1, m02CC;
    be<f32> mVelocityFwdTarget;
    cXyz mPathPosTarget;
    u8 _404[4];
    be<u8> mbCraneMode;
    u8 _409[3];
    be<s32> mCurMode, mPreviousMode;
    WaveCallback_l mWaveLCallback, mWaveRCallback;
    SplashCallback_l mSplashCallback;
    TrackCallback_l mTrackCallback;
    RippleCallback_l mRippleCallback;
    be<u8> mRippleTimer;
    u8 _55D[3];
    cXyz mRipplePos, mWavePos;
    csXyz mWaveRot;
    u8 _57E[2];
    be<f32> mSplashScaleTimer;
    cXyz mTrackPos, mRopeEndPos;
    FollowCallback_l mBombSmokeCallback;
    csXyz mBombSmokeRot;
    u8 _5B6[2];
    cXyz mBombSmokePos;
    be<s32> mBombSmokeTimer;
    be<s16> mBombSmokeAngle;
    u8 _5CA[2];
    FollowCallback_l mFireCallback;
    cXyz mFirePos;
    Mtx34 mLightMtx;
    be<f32> mLightPower, mLightPowerTarget, mGlowRadius, mGlowRadiusTarget;
    be<s32> mEpTimer0, mEpTimer1;
    u8 _634[4];
    be<s32> mTimer;
    u8 _63C[8];
    be<s16> mLightRotX, mLightRotY;
    request_of_phase_process_class mPhase;
    gptr<J3DModel> mpModel;
    mDoExt_bckAnm mBckAnm;
    be<u8> mbIsLinkRiding;
    u8 _6E1[3];
    be<u32> mpBgW;
    Mtx34 mMtx;
    dBgS_ObjAcch mObjAcch;
    dBgS_AcchCir mAcchCir;
    be<u32> mFlagPcId;
    cXyz mFlagOffset;
    be<f32> mFlagScale;
    gptr<J3DModel> mpRopeEnd;
    u8 mRopeLine[0x188];
    be<s32> mRopeCount;
    cXyz mRopeVelocity[200];
    csXyz mJointRot[4];
    be<s32> mHandleFrame;
    gptr<J3DModel> mpSeaModel;
    mDoExt_btkAnm mSeaBtk;
    be<s16> mCraneTarget, mCraneAngle, mCraneAnimPhase, mCraneAmplitude, mLinkRockPhase,
        mLinkRockAmplitude, mWaveAnimPhase;
    be<u8> mStopRequest;
    u8 _14C3;
    be<s32> mDirection;
    be<u32> mSvId[4];
    dCcD_Sph mSph;
    dCcD_Stts mStts;
    be<s32> mHitTimer;
    cXyz mSePos;
    be<s32> mStopTimer;
    Wave_l mWave;
    u8 _1660[4];
    LIGHT_INFLUENCE mPLight;
    cXyz mInitPos;
    be<u8> mHDMotionMode;
    u8 _1695;
    be<s16> mHDPitch, mHDRoll;
    u8 _169A[2];
    be<f32> mHDWaterOffset;
    void modeProc(s32 proc, s32 mode);
    void modeWait();
    void pathMove();
    s32 pathAdvance(cXyz *, cXyz *, cXyz *);
    void modePathMove();
    s32 checkTgHit();
    s32 draw();
    s32 remove();
    void createWave();
    void setWave();
    void epProc();
    s32 execute();
    void setRopePos();
    void setMtx();
    void drawSea();
    s32 create();
    s32 createHeap();
    void createInit();
    void modePathMoveTerry();
    void modeStopTerry();
    void modeStopBombTerry();
    void incRopeCount(s32, s32);
    void modeStop();
    void setCollision();
    void HandleRight();
    void HandleLeft();
    void modeCraneUp();
    void modeCraneUpWaitInit();
    void modeCraneUpWait();
    void modeCraneDownInit();
    void modeCraneDown();
    void modeCraneDownWaitInit();
    void modeCraneDownWait();
    void modeCraneTurnInit();
    void modeCraneTurn();
    void modeCraneResetInit();
    void modeCraneReset();
    void modeCraneWaitInit();
    void modeCraneWait();
    void modePathMoveInit();
    void modePathMoveTerryInit();
    void modeStopTerryInit();
    void getArg();
    void ride(fopAc_ac_c *);
};
WWHD_OFFSET(Actor, mType, 0x3AC);
WWHD_OFFSET(Actor, mCurMode, 0x40C);
WWHD_OFFSET(Actor, mLightMtx, 0x5EC);
WWHD_OFFSET(Actor, mBckAnm, 0x654);
WWHD_OFFSET(Actor, mbIsLinkRiding, 0x6E0);
WWHD_OFFSET(Actor, mObjAcch, 0x718);
WWHD_OFFSET(Actor, mRopeLine, 0x934);
WWHD_OFFSET(Actor, mRopeCount, 0xABC);
WWHD_OFFSET(Actor, mJointRot, 0x1420);
WWHD_OFFSET(Actor, mCraneTarget, 0x14B4);
WWHD_OFFSET(Actor, mSph, 0x14D8);
WWHD_OFFSET(Actor, mPLight, 0x1664);
WWHD_OFFSET(Actor, mInitPos, 0x1688);
WWHD_SIZE(Actor, 0x16A0);
} // namespace ikada
