#pragma once
#include "bindings.h"

struct OshipWave {
    be<s16> angleX, angleZ, animationX, animationZ, rotationX, rotationZ;
};
WWHD_SIZE(OshipWave, 0xC);

// Actor/profile size0xF1C; audited gameplay fields retain the GC order after the HD base.
struct daOship_c : fopAc_ac_c {
    u8 reserved3AC[0x1C];
    be<s32> currentMode;
    be<u8> subMode, switchA, switchB, pathId, triforceMap, salvagePoint, modelType;
    u8 reserved3D3;
    cXyz originalPosition;
    u8 reserved3E0[4];
    cXyz pathStart;
    be<s8> pathPoint;
    u8 reserved3F1[3];
    be<u32> path;
    u8 reserved3F8[4];
    cXyz pathEnd;
    u8 reserved408[0xC];
    be<u8> waveCallbacks[2][0x64];
    be<u8> splashCallback[0x1C];
    be<u8> trackCallback[0x50];
    be<u8> smokeCallbacks[3][0x14];
    cXyz wavePosition;
    csXyz waveRotation;
    u8 reserved596[2];
    be<f32> splashScaleTimer;
    cXyz trackPosition;
    csXyz smokeRotation[3];
    be<s16> smokeYaw[3];
    be<s32> smokeCount;
    request_of_phase_process_class phase;
    be<u32> model;
    be<u8> collisionStatus[0x3C];
    be<u8> cylinders[5][0x130];
    be<u8> groundCollision[0x1C4];
    be<u8> wallCircle[0x40];
    OshipWave wave;
    cXyz targetPosition, bombPosition, smokePosition, flagOffset;
    be<f32> flagMatrix[12];
    be<u32> flagId, bombIds[5];
    be<f32> targetSpeed;
    be<s32> aimCount, hitTimer, attackTimer;
    u8 reservedE94[4];
    be<s32> playerFireTimer;
    be<s16> swayTimer, swayAmount, aimYaw, targetAimYaw, aimPitch, targetAimPitch;
    be<u8> bombAllocated[5];
    u8 reservedEAD[3];
    be<u8> lineCheck[0x6C];
};
WWHD_OFFSET(daOship_c, currentMode, 0x3C8);
WWHD_OFFSET(daOship_c, subMode, 0x3CC);
WWHD_OFFSET(daOship_c, modelType, 0x3D2);
WWHD_OFFSET(daOship_c, originalPosition, 0x3D4);
WWHD_OFFSET(daOship_c, pathStart, 0x3E4);
WWHD_OFFSET(daOship_c, pathPoint, 0x3F0);
WWHD_OFFSET(daOship_c, path, 0x3F4);
WWHD_OFFSET(daOship_c, pathEnd, 0x3FC);
WWHD_OFFSET(daOship_c, waveCallbacks, 0x414);
WWHD_OFFSET(daOship_c, splashCallback, 0x4DC);
WWHD_OFFSET(daOship_c, trackCallback, 0x4F8);
WWHD_OFFSET(daOship_c, smokeCallbacks, 0x548);
WWHD_OFFSET(daOship_c, wavePosition, 0x584);
WWHD_OFFSET(daOship_c, waveRotation, 0x590);
WWHD_OFFSET(daOship_c, splashScaleTimer, 0x598);
WWHD_OFFSET(daOship_c, trackPosition, 0x59C);
WWHD_OFFSET(daOship_c, smokeRotation, 0x5A8);
WWHD_OFFSET(daOship_c, smokeYaw, 0x5BA);
WWHD_OFFSET(daOship_c, smokeCount, 0x5C0);
WWHD_OFFSET(daOship_c, phase, 0x5C4);
WWHD_OFFSET(daOship_c, model, 0x5CC);
WWHD_OFFSET(daOship_c, collisionStatus, 0x5D0);
WWHD_OFFSET(daOship_c, cylinders, 0x60C);
WWHD_OFFSET(daOship_c, groundCollision, 0xBFC);
WWHD_OFFSET(daOship_c, wallCircle, 0xDC0);
WWHD_OFFSET(daOship_c, wave, 0xE00);
WWHD_OFFSET(daOship_c, targetPosition, 0xE0C);
WWHD_OFFSET(daOship_c, bombPosition, 0xE18);
WWHD_OFFSET(daOship_c, smokePosition, 0xE24);
WWHD_OFFSET(daOship_c, flagOffset, 0xE30);
WWHD_OFFSET(daOship_c, flagMatrix, 0xE3C);
WWHD_OFFSET(daOship_c, flagId, 0xE6C);
WWHD_OFFSET(daOship_c, bombIds, 0xE70);
WWHD_OFFSET(daOship_c, targetSpeed, 0xE84);
WWHD_OFFSET(daOship_c, aimCount, 0xE88);
WWHD_OFFSET(daOship_c, hitTimer, 0xE8C);
WWHD_OFFSET(daOship_c, attackTimer, 0xE90);
WWHD_OFFSET(daOship_c, playerFireTimer, 0xE98);
WWHD_OFFSET(daOship_c, swayTimer, 0xE9C);
WWHD_OFFSET(daOship_c, swayAmount, 0xE9E);
WWHD_OFFSET(daOship_c, aimYaw, 0xEA0);
WWHD_OFFSET(daOship_c, targetAimYaw, 0xEA2);
WWHD_OFFSET(daOship_c, aimPitch, 0xEA4);
WWHD_OFFSET(daOship_c, targetAimPitch, 0xEA6);
WWHD_OFFSET(daOship_c, bombAllocated, 0xEA8);
WWHD_OFFSET(daOship_c, lineCheck, 0xEB0);
WWHD_SIZE(daOship_c, 0xF1C);

struct OshipHIOData {
 be<u32> vtable;
 be<u8> debug04, debug05, debug06, debug07, debug08;
 u8 padding09[3];
 be<f32> attentionOffsetY,eyeOffsetY,waveOffsetZ,trackOffsetZ;
 cXyz bombOffset;
 be<f32> rangeA,rangeB,rangeC;
 be<s16> attackDelayA,attackDelayB;
 be<f32> pathSpeed,specularScale,trackOffsetY,trackScaleY;
 be<f32> splashTimerTarget,splashTimerMaximum;
 be<f32> waveFade1,trackVelocity,waveSpeed,waveFadeOffset,waveMaximumVelocity;
 cXyz collapsePosition0,collapsePosition1;
 be<f32> bombSpeed,bombAcceleration;
 be<s16> bombGravityDelay;
 u8 padding86[2];
 be<f32> badAimDistanceStart;
 be<s16> badAimMaximum,angle8E,angle90,node2RotationZ;
};
WWHD_SIZE(OshipHIOData,0x94);
