#pragma once
#include "bindings.h"
// Embedded HD collision objects retain their audited extents. Their internal
// interfaces are accessed through guest calls; gameplay state is named below.
struct BubbleBodyCollider {
    be<u32> attackFlags; be<u32> attackType;
    u8 pad008[0x10]; be<u32> targetFlags; u8 pad01C[0x10]; be<u32> correctionFlags;
    u8 pad030[0x24]; be<u32> contactFlags; u8 pad058[0x58];
    be<u8> targetState; u8 pad0B1; be<u8> targetMaterial;
    u8 pad0B3[0x65]; u8 sphere[0x18]; u8 pad130[0x20];
};
WWHD_OFFSET(BubbleBodyCollider,targetFlags,0x18);
WWHD_OFFSET(BubbleBodyCollider,correctionFlags,0x2C);
WWHD_OFFSET(BubbleBodyCollider,contactFlags,0x54);
WWHD_OFFSET(BubbleBodyCollider,targetState,0xB0);
WWHD_OFFSET(BubbleBodyCollider,sphere,0x118);
WWHD_SIZE(BubbleBodyCollider,0x150);
struct bl_class : fopAc_ac_c {
    u8 pad3AC[0x1C];
    request_of_phase_process_class phase;
    gptr<u8> morph;
    gptr<u8> modelAuxiliary;
    gptr<u8> colorAnimation;
    gptr<u8> textureAnimation;
    cXyz roamingOrigin;
    be<u8> variant;
    be<u8> flying;
    be<u8> action;
    be<u8> burning;
    be<u8> damageKind;
    be<u8> switchNo;
    u8 pad3F2[2];
    be<u32> path;
    u8 pad3F8[0xC];
    be<s8> pathPoint;
    be<u8> pathNo;
    be<s8> stolenItemCount;
    u8 pad407;
    be<s16> timers[6];
    be<s16> spinX;
    be<s16> spinZ;
    be<s16> bounceOrSmokeFade;
    be<s16> skullSmokeFade;
    be<s16> targetYaw;
    be<s16> attackYawOffset;
    be<s16> flightPhase;
    be<s16> actionStep;
    be<s32> animationId;
    u8 pad428[4];
    be<f32> bounceSpeed;
    be<f32> modelYOffset;
    be<f32> targetHeight;
    be<f32> targetScale;
    be<f32> homeGroundHeight;
    be<f32> pathSpeed;
    be<f32> collisionRadius;
    u8 groundCircle[0x40];
    u8 groundCollision[0x1C4];
    u8 bodyCollisionStatus[0x3C];
    BubbleBodyCollider bodyCollider;
    cXyz smokePosition;
    u8 smokeCallback[0x20];
    dPa_followEcallBack appearanceCallback;
    dPa_followEcallBack fireCallback;
    u8 iceState[0x30];
    u8 fireCollisionStatus[0x3C];
    u8 fireCylinder[0x148];
    u8 fireGroundCircle[0x40];
    u8 fireGroundCollision[0x1C4];
    u8 fireHelper[0x22C];
    u8 lightInfo[8];
};
WWHD_OFFSET(bl_class,phase,0x3C8);
WWHD_OFFSET(bl_class,morph,0x3D0);
WWHD_OFFSET(bl_class,roamingOrigin,0x3E0);
WWHD_OFFSET(bl_class,variant,0x3EC);
WWHD_OFFSET(bl_class,path,0x3F4);
WWHD_OFFSET(bl_class,timers,0x408);
WWHD_OFFSET(bl_class,actionStep,0x422);
WWHD_OFFSET(bl_class,targetScale,0x438);
WWHD_OFFSET(bl_class,groundCircle,0x448);
WWHD_OFFSET(bl_class,groundCollision,0x488);
WWHD_OFFSET(bl_class,bodyCollisionStatus,0x64C);
WWHD_OFFSET(bl_class,bodyCollider,0x688);
WWHD_OFFSET(bl_class,smokePosition,0x7D8);
WWHD_OFFSET(bl_class,appearanceCallback,0x804);
WWHD_OFFSET(bl_class,fireCallback,0x818);
WWHD_OFFSET(bl_class,iceState,0x82C);
WWHD_OFFSET(bl_class,fireCollisionStatus,0x85C);
WWHD_OFFSET(bl_class,fireCylinder,0x898);
WWHD_OFFSET(bl_class,fireGroundCircle,0x9E0);
WWHD_OFFSET(bl_class,fireGroundCollision,0xA20);
WWHD_OFFSET(bl_class,fireHelper,0xBE4);
WWHD_OFFSET(bl_class,lightInfo,0xE10);
WWHD_SIZE(bl_class,0xE18);
