#pragma once
#include "bindings.h"
namespace Bigelf {
struct BrkAnimation { u8 frameController[0x78]; };
struct Actor : fopAc_ac_c {
    request_of_phase_process_class phase;
    be<u32> animator;
    BrkAnimation brk;
    mDoExt_btkAnm btk;
    be<u32> flowerModel;
    BrkAnimation flowerBrk;
    be<s8> handJoint;
    u8 reserved521[3];
    dNpc_JntCtrl_c jointController;
    cXyz headPosition,attentionPosition;
    be<u16> reserved570;
    be<s8> animationFinished;
    be<u8> attentionSetCount;
    be<f32> previousFrame;
    be<u32> currentMessage;
    be<u16> stateBits,reserved57E;
    be<u8> messageState,reserved581,givenItem,reserved583;
    be<u32> message,fairy;
    be<s16> headTurn;
    be<u8> lightRegistered,reserved58F;
    cXyz lightPosition;
    be<s16> lightColor[3],reserved5A2;
    be<f32> lightPower,lightFluctuation,reserved5AC,lightIntensity;
    cXyz lightTargetPosition;
    be<s16> lightTargetColor[3],reserved5C6;
    be<f32> lightTargetPower,lightTargetFluctuation,reserved5D0,lightTargetIntensity,reserved5D8,reserved5DC;
    be<u8> darkActive;
    u8 reserved5E1[3];
    be<f32> darkGain,darkTarget,flowerSpeed,flowerFrame;
    be<s16> octTimer,reserved5F6;
    be<s16> actionAdjustment,actionDispatch;
    be<u32> actionTarget;
    be<s8> animation;
    be<u8> state,reserved602,reserved603;
    be<s16> demoCounter,reserved606;
    be<s32> staffID;
    be<s16> eventID,attentionDelay;
    be<u32> appearEmitter;
    cXyz handPosition;
    be<u8> lightState;
    u8 reserved621[3];
    be<u32> changeEmitter,linkEmitter;
    be<f32> fairyHeight,disappearScale,disappearTarget,lightRadius;
    be<s8> initialized,colorType,actionPhase,talking;
    be<u32> octID;
};
WWHD_OFFSET(Actor,animator,0x3B4);
WWHD_OFFSET(Actor,brk,0x3B8);
WWHD_OFFSET(Actor,btk,0x430);
WWHD_OFFSET(Actor,flowerModel,0x4A4);
WWHD_OFFSET(Actor,jointController,0x524);
WWHD_OFFSET(Actor,headPosition,0x558);
WWHD_OFFSET(Actor,stateBits,0x57C);
WWHD_OFFSET(Actor,message,0x584);
WWHD_OFFSET(Actor,lightPosition,0x590);
WWHD_OFFSET(Actor,darkActive,0x5E0);
WWHD_OFFSET(Actor,actionAdjustment,0x5F8);
WWHD_OFFSET(Actor,demoCounter,0x604);
WWHD_OFFSET(Actor,handPosition,0x614);
WWHD_OFFSET(Actor,lightState,0x620);
WWHD_OFFSET(Actor,fairyHeight,0x62C);
WWHD_OFFSET(Actor,talking,0x63F);
WWHD_SIZE(Actor,0x644);
}
