#pragma once
#include "f_op/f_op_actor.h"
struct daObjTapestryPacket_c;
struct daObjTapestry_c : fopAc_ac_c {
  u8 mPhase[8];
  gptr<daObjTapestryPacket_c> mpPacket;
  gptr<u8> mpModel, mpBg;
  be<f32> mBgMatrix[12];
  u8 mTriangles[0x2A0], mCollisionStatus[0x78];
  be<s16> mBurnTimer;
  be<u8> mBurned;
  u8 _70B;
  be<s16> mEvent;
  u8 _70E[2];
  be<f32> mOpacity;
  be<u32> mActionDescriptor[2];
  be<s32> mAction;
  s32 create_res_load();
  BOOL create_heap();
  void set_mtx();
  void init_mtx();
  BOOL chk_appear();
  void setup_action(s32);
  BOOL _delete();
  BOOL _execute();
  void set_cc_pos();
  void init_cc();
  void set_eye_pos();
  s32 _create();
  BOOL _draw();
  void wait_act_proc();
  void demo_request_act_proc();
  void burn_act_proc();
};
WWHD_OFFSET(daObjTapestry_c, mActionDescriptor, 0x714);
WWHD_SIZE(daObjTapestry_c, 0x720);
struct TapestryMaterialGroup {
  gptr<u8> mpDefinition;
  be<u32> mFrontCount;
  gptr<u8> mpFrontVectors;
  be<u32> mBackCount;
  gptr<u8> mpBackVectors;
};
WWHD_SIZE(TapestryMaterialGroup, 0x14);
struct TapestryVertexBuffer {
  gptr<u8> mpData;
  u8 mAttributes[0x248];
  be<u32> mVertexCount;
  gptr<u8> mpOwnedData;
};
WWHD_SIZE(TapestryVertexBuffer, 0x254);
struct daObjTapestryPacket_c {
  u8 _000[0x98];
  be<u32> mMaterialCount, mMaterialCapacity;
  gptr<TapestryMaterialGroup> mpMaterialGroups;
  TapestryVertexBuffer mVertexBuffers[2][2];
  be<u32> mVertexBuffer, mVertexFormat;
  u8 _9FC[4];
  gptr<u8> mpVertexLayout;
  be<u32> mRenderMode;
  be<u8> mRenderEnabled;
  u8 _A09[3];
  u8 _A0C[0x654];
  be<u8> mTextureFlags;
  u8 _1061[11];
  cXyz mPositions[2][144];
  cXyz mVelocity[48];
  be<u8> mVertexFlags[48], mFireTimers[48], mFireIndices[48];
  be<u32> mPositionBuffer;
  u8 mFireCallbacks[16][0x2C];
  be<s32> mFireCount;
  cXyz mAcceleration;
  be<f32> mWorldMatrix[12], mViewMatrix[12], mInverseMatrix[12];
  be<u8> mInverseValid;
  u8 _2421[3];
  cXyz mWorldWind, mWind;
  be<s16> mWindPhase;
  u8 _243E[2];
  cXyz mFlutter;
  be<s16> mFlutterAngles[3];
  u8 _2452[2];
  cXyz mTopWind, mMiddleWind, mBottomWind;
  cXyz mHitPosition, mLocalHitPosition, mHitDirection, mLocalHitDirection;
  be<f32> mHitForce, mHitRadius;
  be<u8> mHitFire;
  u8 _24B1[3];
  be<f32> mHitAttenuation, mHitRow, mHitColumn;
  be<u8> mDetached, mGroundCollision, mSmokeType;
  u8 _24C3;
  u8 mSmokeCallback[0x2C];
  u8 mLight[0x30];
  cXyz *get_now_pos(s32, s32);
  void calc_acc_gravity();
  void eff_end();
  void eff_delete();
  void smokeCallback_init();
};
WWHD_OFFSET(daObjTapestryPacket_c, mVertexBuffers, 0xA4);
WWHD_OFFSET(daObjTapestryPacket_c, mVertexBuffer, 0x9F4);
WWHD_OFFSET(daObjTapestryPacket_c, mPositions, 0x106C);
WWHD_OFFSET(daObjTapestryPacket_c, mWorldWind, 0x2424);
WWHD_OFFSET(daObjTapestryPacket_c, mPositionBuffer, 0x20BC);
WWHD_OFFSET(daObjTapestryPacket_c, mAcceleration, 0x2384);
WWHD_SIZE(daObjTapestryPacket_c, 0x2520);
struct daObjTapestryPLight_c {
  be<u8> mActive;
  u8 _1[3];
  u8 mInfluence[0x20];
  be<f32> mPower;
  gptr<u8> mpEmitter;
  u8 _2C[4];
  void plight_make();
  void plight_delete();
};
WWHD_SIZE(daObjTapestryPLight_c, 0x30);
