/* daGrid_c / daHo_packet_c (ship sail), WWHD layout. */
#pragma once
#include "bindings.h"
struct SailGpuMaterial_l {
  gptr<void> vertices;
  u8 vertexBuffer[0x154];
  u8 shaderObject[0xF4];
  be<u32> allocationCount;
  gptr<void> allocation;
};
WWHD_SIZE(SailGpuMaterial_l, 0x254);
struct SailMaterialPool_l {
  SailGpuMaterial_l materials[4];
  be<u32> current;
  be<u32> attributeCount;
  be<u32> stride;
  gptr<void> attributes;
  be<u32> unused;
  be<u8> initialized;
  u8 padding[3];
};
WWHD_SIZE(SailMaterialPool_l, 0x968);
struct SailShaderCollection_l {
  gptr<void> program;
  be<s32> frontShaderCount;
  gptr<void> frontShaders;
  be<s32> backShaderCount;
  gptr<void> backShaders;
};
WWHD_SIZE(SailShaderCollection_l, 0x14);
WWHD_OFFSET(SailShaderCollection_l, frontShaders, 8);
WWHD_OFFSET(SailShaderCollection_l, backShaders, 0x10);
struct daHo_packet_c {
  u8 packetBase[0xAC];
  Mtx34 matrix;
  gptr<void> lighting;
  cXyz positions[85];
  cXyz normals[85];
  cXyz backNormals[85];
  be<s16> normalAngle, unusedAngle1, unusedAngle2;
  be<u8> alpha;
  u8 paddingCDB;
  be<u32> shaderCount;
  be<u32> shaderCollectionCount;
  gptr<SailShaderCollection_l> shaderCollections;
  SailMaterialPool_l materialPool;
  be<u32> drawMaterialCount;
  gptr<void> drawMaterials;
  u8 drawMaterialState[0x78];
  Mtx34 modelMatrix;
  be<u32> modelFlags;
  u8 materialUniformObject[0x74];
  u8 uniformState[0x2F0];
  be<u8> uniformFlag;
  u8 padding1A69[3];
  u8 indexBuffer[0x18];
  u8 frontTexture[0x198];
  u8 frontTextureResource[0x90];
  u8 alternateTexture[0x198];
  u8 alternateTextureResource[0x90];
  u8 toonTexture[0x198];
  u8 toonTextureResource[0x90];
  be<u8> textureInitialized;
  u8 padding20FD[3];
};
WWHD_SIZE(daHo_packet_c, 0x2100);
WWHD_OFFSET(daHo_packet_c, matrix, 0xAC);
WWHD_OFFSET(daHo_packet_c, lighting, 0xDC);
WWHD_OFFSET(daHo_packet_c, positions, 0xE0);
WWHD_OFFSET(daHo_packet_c, normals, 0x4DC);
WWHD_OFFSET(daHo_packet_c, backNormals, 0x8D8);
WWHD_OFFSET(daHo_packet_c, normalAngle, 0xCD4);
WWHD_OFFSET(daHo_packet_c, alpha, 0xCDA);
WWHD_OFFSET(daHo_packet_c, shaderCount, 0xCDC);
WWHD_OFFSET(daHo_packet_c, shaderCollectionCount, 0xCE0);
WWHD_OFFSET(daHo_packet_c, shaderCollections, 0xCE4);
WWHD_OFFSET(daHo_packet_c, materialPool, 0xCE8);
WWHD_OFFSET(daHo_packet_c, drawMaterialCount, 0x1650);
WWHD_OFFSET(daHo_packet_c, modelMatrix, 0x16D0);
WWHD_OFFSET(daHo_packet_c, uniformState, 0x1778);
WWHD_OFFSET(daHo_packet_c, indexBuffer, 0x1A6C);
WWHD_OFFSET(daHo_packet_c, frontTexture, 0x1A84);
WWHD_OFFSET(daHo_packet_c, alternateTexture, 0x1CAC);
WWHD_OFFSET(daHo_packet_c, toonTexture, 0x1ED4);
WWHD_OFFSET(daHo_packet_c, textureInitialized, 0x20FC);
struct daGrid_c : fopAc_ac_c {
  request_of_phase_process_class clothPhase;
  request_of_phase_process_class shipPhase;
  daHo_packet_c packet;
  be<u32> wavePhase;
  be<s8> parameter;
  u8 padding24C1;
  be<s16> openingTimer;
  be<s16> waveStepSin;
  be<s16> waveStepCos;
  u8 padding24C8[4];
  be<f32> weights[85];
  u8 unusedClothState[0x558];
  be<f32> furl;
  be<f32> openingGain;
  be<f32> openingStarted;
  be<f32> oscillationGain;
  be<f32> oscillationSign;
  be<s16> oscillationTimer;
  u8 padding2B8E[6];
  be<s16> relativeWindAngle;
  be<s16> twistAngle;
  be<s16> unusedAngle;
  be<s16> forcedWindAngle;
  be<u8> forceWind;
  u8 padding2B9D[3];
};
WWHD_SIZE(daGrid_c, 0x2BA0); // HD profile101B6B18.
WWHD_OFFSET(daGrid_c, packet, 0x3BC);
WWHD_OFFSET(daGrid_c, wavePhase, 0x24BC);
WWHD_OFFSET(daGrid_c, weights, 0x24CC);
WWHD_OFFSET(daGrid_c, furl, 0x2B78);
WWHD_OFFSET(daGrid_c, relativeWindAngle, 0x2B94);
WWHD_OFFSET(daGrid_c, forceWind, 0x2B9C);
