#!/usr/bin/env python3
"""Argument registers of the game's imports (2026-10-05, game test: d_a_grid / d_a_pirate_flag called
GX2CallDisplayList without its size argument r4; for imports the harness only compared the registers
the candidate declares, so the omission was invisible).

usage: import_args.py            writes tools/verify/import_args.tsv (slot, name, GPR mask, FPR mask, source)

Sources, per import (build/gen/imports.json):
  1. the runtime's HLE implementation (runtime/src/**/*.cpp, `HLE(lib, Name) { ... }`): every argument it
     reads - arg(c, i) = r3+i, arg64(c, R) = rR and rR+1, c->r[N] read, fa(c, i) / farg(c, i) = f1+i,
     c->f[N] read. A lower bound: helpers the body calls with `c` are not followed.
  2. the CodeWarrior-mangled name (C++ SDK imports such as nn::act): the parameter list of the mangling.
The union of both is used. mkunit.py compares these registers at every call of the import, in addition
to what the candidate declares, so an argument the candidate omits shows up as a register difference."""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, HERE)
from funcdb import signature, arg_regs  # noqa: E402


def hle_bodies():
    out = {}
    for dp, _, fs in os.walk(os.path.join(ROOT, "runtime", "src")):
        for f in fs:
            if not f.endswith((".cpp", ".c")):
                continue
            text = open(os.path.join(dp, f), errors="replace").read()
            for m in re.finditer(r"\bHLE\(\s*(\w+)\s*,\s*(\w+)\s*\)\s*\{", text):
                i, depth = m.end(), 1
                while i < len(text) and depth:
                    depth += {"{": 1, "}": -1}.get(text[i], 0)
                    i += 1
                out.setdefault(m.group(2), []).append((os.path.relpath(os.path.join(dp, f), ROOT), text[m.end():i]))
    return out


def regs_of_body(body):
    g, fl = set(), set()
    for m in re.finditer(r"\barg\(\s*c\s*,\s*(\d+)\s*\)", body):
        g.add(3 + int(m.group(1)))
    for m in re.finditer(r"\barg64\(\s*c\s*,\s*(\d+)\s*\)", body):
        g |= {int(m.group(1)), int(m.group(1)) + 1}
    for m in re.finditer(r"c->r\[(\d+)\](?!\s*=[^=])", body):
        g.add(int(m.group(1)))
    for m in re.finditer(r"\b(?:fa|farg)\(\s*c\s*,\s*(\d+)\s*\)", body):
        fl.add(1 + int(m.group(1)))
    for m in re.finditer(r"c->f\[(\d+)\](?:\.ps0)?(?!\s*(?:\.ps[01])?\s*=[^=])", body):
        fl.add(int(m.group(1)))
    return {r for r in g if 3 <= r <= 10}, {r for r in fl if 1 <= r <= 8}


def main():
    imps = json.load(open(os.path.join(ROOT, "build", "gen", "imports.json")))
    bodies = hle_bodies()
    rows = []
    for e in imps:
        if e.get("kind", "f") != "f":
            continue
        name = e["name"]
        g, fl, src = set(), set(), []
        for path, body in bodies.get(name, []):
            a, b = regs_of_body(body)
            g |= a
            fl |= b
            src.append("hle:" + path)
        # GHS mangling writes qualifiers as Q2_2nn3act; the CodeWarrior demangler expects Q22nn3act. A
        # lower-case innermost qualifier is a namespace (nn::act::Initialize), else a class (this in r3).
        norm = re.sub(r"Q(\d)_", r"Q\1", name)
        sig = signature(norm) if "__" in name else None
        if sig:
            try:
                _, params = sig
                quals = []
                k = norm.find("__", 1) + 2
                n = 1
                if norm[k:k + 1] == "Q":
                    n, k = int(norm[k + 1]), k + 2
                for _ in range(n):
                    m = re.match(r"(\d+)", norm[k:])
                    if not m:
                        break
                    ln = int(m.group(1))
                    quals.append(norm[k + len(m.group(1)):k + len(m.group(1)) + ln])
                    k += len(m.group(1)) + ln
                method = bool(quals) and not quals[-1][:1].islower() and not name.startswith("__")
                if name.startswith("__ct__") or name.startswith("__dt__"):
                    method = True
                ints, flts, _ = arg_regs(method, params)
                g |= set(ints)
                fl |= set(flts)
                src.append("mangled")
            except Exception:
                pass
        if not g and not fl:
            continue
        gm = sum(1 << r for r in g)
        fm = sum(1 << r for r in fl)
        rows.append("%08X\t%s\t0x%X\t0x%X\t%s" % (e["slot"], name, gm, fm, ",".join(src)))
    out = os.path.join(HERE, "import_args.tsv")
    with open(out, "w") as f:
        f.write("# Generated by import_args.py: argument registers of imports (slot, name, GPR mask, FPR mask, source).\n")
        f.write("# mkunit.py compares them at every import call (plus what the candidate declares).\n")
        f.write("\n".join(sorted(rows)) + "\n")
    print("%d imports with known argument registers -> %s" % (len(rows), out))


if __name__ == "__main__":
    main()
